name: Upload EC2 API

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    branches:
      - master

jobs:
  deploy-api:
    runs-on: ubuntu-latest
  
    steps:
    - name: Get Code Latest Version
      uses: actions/checkout@v2 
    
    - name: Serverless deploy
      uses: serverless/github-action@v3
      with:
        args: deploy --stage ${opt:stage, 'dev'} 
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}