name: Upload API Gateway

on:
  push:
    tags:
      - '*'

  workflow_dispatch:
    branches:
      - master

jobs:
  deploy-api:
    runs-on: ubuntu-latest
  
    steps:
    - name: Get Code Latest Version
      uses: actions/checkout@v2 
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 14.x

    - name: Install Serverless Framework
      run: npm install -g serverless

    - name: Serverless Authentication
      run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Deploy to AWS
      run: |
        cd api
        serverless deploy