name: Upload EC2 API

on:
  # tags:
  #   - v1.*
  #   - v2.*

  workflow_dispatch:
    branches:
    - master

jobs:
  deploy-api:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2 # pegar a versao mais atualizada do codigo
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 14.x

    - name: Install dependencies
      run: |
        cd login-api
        npm install
    
    - name: Run build
      run: |
        cd login-api
        npm run build
      
    - name: copy dist to ec2 machine
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app2"
      
    - name: Install dependencies on digital ocean and restart server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app2/cloudfront-demo-project/login-api
            npm install
            pm2 kill
            pm2 start dist/main.js —name loginapi

