name: Upload EC2 API

on:
  tags:
    - v1.*
    - v2.*

  workflow_dispatch:
    branches:
    - master

jobs:
  deploy-api:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2 # pegar a versao mais atualizada do codigo
    
    # instalar node
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 14.x

    # instalar as dependencias          
    - name: Install dependencies
      run: npm install
    
    executar a build
    - name: Run build
      run: npm run-script build
      
    # copy code to ec2 machine    
    - name: copy dist to digital ocean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        key: ${{ secrets.SSH_KEY }}
        source: ".,!node_modules"
        target: "~/app/cloudfront-demo-project/login-api"
      
    # install dependencies
    - name: Install dependencies on digital ocean and restart server
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/cloudfront-demo-project/login-api
            npm install
            pm2 kill
            pm2 start dist/main.js —name loginapi

